// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaerRkdqZpa4jH-1RNlVlH3ZzRQl-3JBg',
    appId: '1:409095745497:web:60ac48ddf5e7b14d8373c8',
    messagingSenderId: '409095745497',
    projectId: 'todolist-3b056',
    authDomain: 'todolist-3b056.firebaseapp.com',
    storageBucket: 'todolist-3b056.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqtwe9X6ODGiZSoz_pKUg6a_sWYKhS9ts',
    appId: '1:409095745497:android:71470aa50b0c98138373c8',
    messagingSenderId: '409095745497',
    projectId: 'todolist-3b056',
    storageBucket: 'todolist-3b056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6CUcqRORWSFMmbImgK8V10dmfaFnw1xM',
    appId: '1:409095745497:ios:1b19ffeb5d12f6b88373c8',
    messagingSenderId: '409095745497',
    projectId: 'todolist-3b056',
    storageBucket: 'todolist-3b056.firebasestorage.app',
    iosBundleId: 'com.example.breakoutRoomActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6CUcqRORWSFMmbImgK8V10dmfaFnw1xM',
    appId: '1:409095745497:ios:1b19ffeb5d12f6b88373c8',
    messagingSenderId: '409095745497',
    projectId: 'todolist-3b056',
    storageBucket: 'todolist-3b056.firebasestorage.app',
    iosBundleId: 'com.example.breakoutRoomActivity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaerRkdqZpa4jH-1RNlVlH3ZzRQl-3JBg',
    appId: '1:409095745497:web:fc65f7e864c3f5568373c8',
    messagingSenderId: '409095745497',
    projectId: 'todolist-3b056',
    authDomain: 'todolist-3b056.firebaseapp.com',
    storageBucket: 'todolist-3b056.firebasestorage.app',
  );
}
